//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmaster3000_Mironow_Volkov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksCovers
    {
        public long Id { get; set; }
        public byte[] CoverFile { get; set; }
        public string Book_Key { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
