//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmaster3000_Mironow_Volkov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.BookList = new HashSet<BookList>();
            this.BooksCovers = new HashSet<BooksCovers>();
            this.Issue = new HashSet<Issue>();
        }
    
        public string Key { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string FirstPublishDate { get; set; }
        public string Description { get; set; }
        public string Cover { get; set; }
    
        public virtual ICollection<BookList> BookList { get; set; }
        public virtual ICollection<BooksCovers> BooksCovers { get; set; }
        public virtual ICollection<Issue> Issue { get; set; }
    }
}
