//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmaster3000_Mironow_Volkov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookList
    {
        public int ListId { get; set; }
        public string KeyToBooks { get; set; }
        public string KeyToAuthors { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Books Books { get; set; }
    }
}
