//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmaster3000_Mironow_Volkov.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int IssueId { get; set; }
        public string BookID { get; set; }
        public string Book { get; set; }
        public string CustomerID { get; set; }
        public string Customer { get; set; }
        public string DateOfIssue { get; set; }
        public string ReturnDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
