//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmaster3000_Mironow_Volkov.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoockMaster3000MiRoNoV123Entities : DbContext
    {
        public BoockMaster3000MiRoNoV123Entities()
            : base("name=BoockMaster3000MiRoNoV123Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Authors> Authors { get; set; }
        public DbSet<BookList> BookList { get; set; }
        public DbSet<Books> Books { get; set; }
        public DbSet<BooksCovers> BooksCovers { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<Issue> Issue { get; set; }
    }
}
